[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "test_utils"
path = "lib.rs"

[dependencies]
common = { path = "../common", features = ["db", "settings"]}

sea-orm.workspace = true