[env]
RUST_BACKTRACE=0

# server
[tasks.run]
workspace = false
command = "cargo"
args = ["run", "--bin", "life_tracker"]

# tests
[tasks.init_test_db]
workspace = false
command = "cargo"
args = ["run", "--bin", "init_test_db"]

[tasks._test]
workspace = false
command = "cargo"
args = ["test", "--no-fail-fast", "--all-targets", "--workspace"]

[tasks.test_quiet]
workspace = false
command = "cargo"
args = ["test", "-q", "--no-fail-fast", "--all-targets", "--workspace"]

[tasks.tt]
workspace = false
dependencies = [
    "init_test_db",
    "_test"
]

[tasks.tq]
workspace = false
dependencies = [
    "init_test_db",
    "test_quiet"
]
