max_width = 115
# hard_tabs = false
# tab_spaces = 4
# newline_style = "Auto"
# indent_style = "Block"
# use_small_heuristics = "Default"
# fn_call_width = 60  115がいいかも
attr_fn_like_width = 115
struct_lit_width = 115
# skip_macro_invocations = []
# hex_literal_case = "Preserve"
# float_literal_trailing_zero = "Preserve"
# imports_indent = "Block"
# imports_layout = "Mixed"
# imports_granularity = "Preserve"
# group_imports = "Preserve"
# type_punctuation_density = "Wide"
# binop_separator = "Front"
# short_array_element_width_threshold = 10
# struct_field_align_threshold = 0
# enum_discrim_align_threshold = 0
# match_arm_leading_pipes = "Never"
# fn_params_layout = "Tall"
# brace_style = "SameLineWhere"
# control_brace_style = "AlwaysSameLine"
# trailing_comma = "Vertical"
# match_block_trailing_comma = false
# blank_lines_upper_bound = 1
# blank_lines_lower_bound = 0
# edition = "2015"
# style_edition = "2015"
# version = "One"
# inline_attribute_width = 0
# format_generated_files = true
# generated_marker_line_search_limit = 5
# merge_derives = true
# use_try_shorthand = false
# use_field_init_shorthand = false
# force_explicit_abi = true
# condense_wildcard_suffixes = false
# color = "Auto"
# required_version = "1.9.0"
# unstable_features = false
# disable_all_formatting = false
# skip_children = false
# show_parse_errors = true
# error_on_line_overflow = false
# error_on_unformatted = false
# ignore = []
# emit_mode = "Files"
# make_backup = false
