application:
  protocol: https
  host: 0.0.0.0
  # MYMEMO: Fill this. Maybe better in .env?
  base_url: ""

debug: false

secret:
  token_expiration: 30

# MYMEMO: Fill this. Maybe better in .env?
frontend_url: "https://localhost:3000"
