# Turn on debug to use these.
###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

# ###
# # @name list
# GET {{endpoint}}/api/action_goals

@action_id=9420a11f-a1fa-46e2-82fe-a5a79bd79a75

###
# @name set_new
POST {{endpoint}}/api/action_goals
Content-Type: application/json

{
  "action_id": "{{action_id}}",
  "duration_seconds": 3600,
  "count": null
}

# ###
# # @name delete
# DELETE {{endpoint}}/api/action_goals/{{action_id}}
