# Actions

###
# @name login
POST {{endpoint}}/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
# @name list
GET {{endpoint}}/actions

@action_id=dbfee866-97ec-4876-b309-c1e36c52ad44

###
# @name get
GET {{endpoint}}/actions/{{action_id}}

###
# @name create
POST {{endpoint}}/actions
Content-Type: application/json

{
  "name": "Second action"
}

###
# @name update
PUT {{endpoint}}/actions/{{action_id}}
Content-Type: application/json

{
  "name": "My action edited"
}

# MYMEMO: can be deleted freely, as no records will be cascade deleted.
###
# @name delete
DELETE {{endpoint}}/actions/{{action_id}}

