# ActionTracks
# Turn on debug to use these.
###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
# @name list
GET {{endpoint}}/api/action_tracks

###
# @name list_active_only
GET {{endpoint}}/api/action_tracks?active_only=true

###
# @name list_by_date
GET {{endpoint}}/api/action_tracks/by_date

@action_track_id=01978573-64cf-70f0-aaca-e09c7503d398
@action_id="4ea4010c-05bd-4607-9199-8d07f8ba7d03"

###
# @name create
POST {{endpoint}}/api/action_tracks
Content-Type: application/json

{
  "started_at": "2024-12-27T12:51:04.000Z",
  "ended_at": null,
  "action_id": {{action_id}}
}

###
# @name update
PUT {{endpoint}}/api/action_tracks/{{action_track_id}}
Content-Type: application/json

{
  "started_at": "2024-12-29T12:50:04.000Z",
  "ended_at": "2024-12-29T13:55:25.700Z",
  "action_id": {{action_id}}
}

###
# @name delete
DELETE {{endpoint}}/api/action_tracks/{{action_track_id}}

###
# @name aggregation_by_timestamp_range
GET {{endpoint}}/api/action_tracks/aggregation?started_at_gte=2025-06-01T15:00:00Z&started_at_lte=2025-06-06T14:59:59Z

###
# @name aggregation_by_dates
GET {{endpoint}}/api/action_tracks/aggregation?dates=20250602,20250603,20250604,20250605,20250606


