# Turn on debug to use these.
###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name list
GET {{endpoint}}/api/actions

@action_id=9420a11f-a1fa-46e2-82fe-a5a79bd79a75

###
# @name get
GET {{endpoint}}/api/actions/{{action_id}}

###
# @name create
POST {{endpoint}}/api/actions
Content-Type: application/json

{
  "name": "Second action",
  "discipline": "Second action discipline",
  "memo": "Second action memo",
  "track_type": "Count"
}

###
# @name update
PUT {{endpoint}}/api/actions/{{action_id}}
Content-Type: application/json

{
  "name": "My action edited",
  "discipline": "Discipline added",
  "memo": "memo added",
  "color": "#adfadf"
}

###
# @name convert_track_type
PUT {{endpoint}}/api/actions/{{action_id}}/track_type
Content-Type: application/json

{
  "track_type": "TimeSpan"
}

###
# @name delete
DELETE {{endpoint}}/api/actions/{{action_id}}

###
# @name bulk_update_ordering
PUT {{endpoint}}/api/actions/bulk_update_ordering
Content-Type: application/json

{
  "ordering": [
    "b9b1b04f-4553-4fd8-9053-801047b7b181",
    "be7974b1-0d9c-497b-a862-3d45d119de3f"
  ]
}

