# Memos
# Turn on debug to use these.
###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
# @name list
GET {{endpoint}}/api/memos

@memo_id=1b4fb4b2-5e13-4ede-a4e9-8e14beb66a37
@tag_0_id="8ae47c10-d248-46e2-9986-b17b1944ec70"
@tag_1_id="73d61c99-3ab9-44b7-a732-f773c845b27d"

###
# @name create
POST {{endpoint}}/api/memos
Content-Type: application/json

{
  "title": "Second memo",
  "text": "This is my second memo.",
  "date": "2024-11-24",
  "tag_ids": [{{tag_0_id}}, {{tag_1_id}}]
}

###
# @name update
PUT {{endpoint}}/api/memos/{{memo_id}}
Content-Type: application/json

{
  "title": "Second memo edited",
  "text": "This is my second memo edited.",
  "date": null,
  "tag_ids": null
}

###
# @name delete
DELETE {{endpoint}}/api/memos/{{memo_id}}

