# Objectives
# Turn off debug to use these.
###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
# @name list
GET {{endpoint}}/api/objectives

@objective_id=3bea9c2e-0db8-4e77-9d91-529972f9786c

###
# @name get
GET {{endpoint}}/api/objectives/{{objective_id}}

###
# @name create
POST {{endpoint}}/api/objectives
Content-Type: application/json

{
  "name": "Second objective"
}

###
# @name update
PUT {{endpoint}}/api/objectives/{{objective_id}}
Content-Type: application/json

{
  "name": "My objective edited"
}

###
# @name delete
DELETE {{endpoint}}/api/objectives/{{objective_id}}

@action_id=f28ac87e-abb2-403a-a451-b973e79e636c

###
# @name connect
POST {{endpoint}}/api/objectives/{{objective_id}}/actions/{{action_id}}/connection
Content-Type: application/json

###
# @name disconnect
DELETE {{endpoint}}/api/objectives/{{objective_id}}/actions/{{action_id}}/connection

