# Tags
# Turn on debug to use these.
###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
# @name create
POST {{endpoint}}/api/tags/plain
Content-Type: application/json

{
  "name": "Plain tag"
}

###
# @name list
GET {{endpoint}}/api/tags

@tag_id=01963d4c-176a-7972-8a4b-a08723212141

###
# @name update
PUT {{endpoint}}/api/tags/plain/{{tag_id}}
Content-Type: application/json

{
  "name": "Plain tag edited"
}

###
# @name delete
DELETE {{endpoint}}/api/tags/plain/{{tag_id}}
