# Users

###
# @name register
POST {{endpoint}}/users/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "first_name": "Lynx",
  "last_name": "Levin"
}

###
# @name confirm
GET {{endpoint}}/users/register/confirm?token=

###
# @name login
POST {{endpoint}}/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


###
# @name logout
POST {{endpoint}}/users/logout
Content-Type: application/json
