//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "action_goal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "action_goal_to_date_unique_index")]
    pub user_id: Uuid,
    #[sea_orm(unique_key = "action_goal_to_date_unique_index")]
    pub action_id: Uuid,
    #[sea_orm(unique_key = "action_goal_from_date_unique_index")]
    pub from_date: Date,
    #[sea_orm(unique_key = "action_goal_to_date_unique_index")]
    pub to_date: Option<Date>,
    pub duration_seconds: Option<i32>,
    pub count: Option<i32>,
    #[sea_orm(belongs_to, from = "action_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub action_item: HasOne<super::action::Entity>,
    #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
