//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use chrono::Utc;
use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr, ActiveValue::Set};
use serde::{Deserialize, Serialize};

// MYMEMO: マイグレーション問題なく動くか確認
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "action")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub discipline: Option<String>,
    pub archived: bool,
    pub ordering: Option<i32>,
    #[sea_orm(column_type = "String(StringLen::N(7))")]
    pub color: String,
    pub track_type: ActionTrackType,
    pub memo: Option<String>,
    #[sea_orm(has_many)]
    pub action_goals: HasMany<super::action_goal::Entity>,
    #[sea_orm(has_many)]
    pub action_tracks: HasMany<super::action_track::Entity>,
    #[sea_orm(has_many)]
    pub notification_rules: HasMany<super::notification_rule::Entity>,
    #[sea_orm(has_one)]
    pub tag: HasOne<super::tag::Entity>,
    #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub user: HasOne<super::user::Entity>,
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum ActionTrackType {
    Count,
    TimeSpan,
}

impl FromStr for ActionTrackType {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Count" => Ok(Self::Count),
            "TimeSpan" => Ok(Self::TimeSpan),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for ActionTrackType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Count => "Count",
                Self::TimeSpan => "TimeSpan",
            }
        )
    }
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            archived: Set(false),
            color: Set("#212121".to_string()),
            created_at: Set(Utc::now().into()),
            updated_at: Set(Utc::now().into()),
            ..ActiveModelTrait::default()
        }
    }
}
