//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "action")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub discipline: Option<String>,
    pub archived: bool,
    pub ordering: Option<i32>,
    pub color: String,
    pub track_type: ActionTrackType,
    pub memo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::action_goal::Entity")]
    ActionGoal,
    #[sea_orm(has_many = "super::action_track::Entity")]
    ActionTrack,
    #[sea_orm(has_many = "super::notification_rule::Entity")]
    NotificationRule,
    #[sea_orm(has_one = "super::tag::Entity")]
    Tag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::action_goal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActionGoal.def()
    }
}

impl Related<super::action_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActionTrack.def()
    }
}

impl Related<super::notification_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationRule.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum ActionTrackType {
    Count,
    TimeSpan,
}

impl FromStr for ActionTrackType {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Count" => Ok(Self::Count),
            "TimeSpan" => Ok(Self::TimeSpan),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for ActionTrackType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Count => "Count",
                Self::TimeSpan => "TimeSpan",
            }
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
