//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "desired_states_actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub desired_state_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub action_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::action::Entity",
        from = "Column::ActionId",
        to = "super::action::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Action,
    #[sea_orm(
        belongs_to = "super::desired_state::Entity",
        from = "Column::DesiredStateId",
        to = "super::desired_state::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DesiredState,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::desired_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DesiredState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
