//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "diary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub positive_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub negative_text: Option<String>,
    pub date: Date,
    pub score: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::diaries_tags::Entity")]
    DiariesTags,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::diaries_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiariesTags.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::diaries_tags::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::diaries_tags::Relation::Diary.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
