//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod action;
pub mod ambition;
pub mod ambitions_objectives;
pub mod book_excerpt;
pub mod book_excerpts_tags;
pub mod memo;
pub mod memos_tags;
pub mod mission_memo;
pub mod mission_memos_tags;
pub mod objective;
pub mod objectives_actions;
pub mod record;
pub mod sea_orm_active_enums;
pub mod tag;
pub mod user;
