//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod action;
pub mod ambition;
pub mod objective;
pub mod record;
pub mod sea_orm_active_enums;
pub mod tag;
pub mod user;
