//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use chrono::Weekday;
use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_rule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub weekday: i16,
    pub utc_time: Time,
    pub action_id: Option<Uuid>,
    pub r#type: NotificationType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::action::Entity",
        from = "Column::ActionId",
        to = "super::action::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Action,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum NotificationType {
    Ambition,
    AmbitionOrDirection,
    Direction,
    UnaccomplishedAction,
}

impl FromStr for NotificationType {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Ambition" => Ok(Self::Ambition),
            "AmbitionOrDirection" => Ok(Self::AmbitionOrDirection),
            "Direction" => Ok(Self::Direction),
            "UnaccomplishedAction" => Ok(Self::UnaccomplishedAction),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for NotificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Ambition => "Ambition",
                Self::AmbitionOrDirection => "AmbitionOrDirection",
                Self::Direction => "Direction",
                Self::UnaccomplishedAction => "UnaccomplishedAction",
            }
        )
    }
}

impl Model {
    pub fn get_utc_weekday(&self) -> Weekday {
        match self.weekday {
            0 | 1 | 2 | 3 | 4 | 5 | 6 => {
                let weekday: u8 = self.weekday.try_into().unwrap();
                Weekday::try_from(weekday).unwrap()
            }
            _ => unreachable!("This should not happen, weekday has DB check to make sure it's between 0 to 6."),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
