//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use chrono::Weekday;
use sea_orm::{
    entity::prelude::{async_trait::async_trait, *},
    sea_query::ValueTypeErr,
    ActiveValue::Set,
};
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_rule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub weekday: i16,
    pub utc_time: Time,
    pub action_id: Option<Uuid>,
    pub r#type: NotificationType,
    #[sea_orm(belongs_to, from = "action_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub action_item: HasOne<super::action::Entity>,
    #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub user: HasOne<super::user::Entity>,
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum NotificationType {
    Ambition,
    AmbitionOrDirection,
    Direction,
    UnaccomplishedAction,
}

impl FromStr for NotificationType {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Ambition" => Ok(Self::Ambition),
            "AmbitionOrDirection" => Ok(Self::AmbitionOrDirection),
            "Direction" => Ok(Self::Direction),
            "UnaccomplishedAction" => Ok(Self::UnaccomplishedAction),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for NotificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Ambition => "Ambition",
                Self::AmbitionOrDirection => "AmbitionOrDirection",
                Self::Direction => "Direction",
                Self::UnaccomplishedAction => "UnaccomplishedAction",
            }
        )
    }
}

impl Model {
    pub fn get_utc_weekday(&self) -> Weekday {
        match self.weekday {
            0 | 1 | 2 | 3 | 4 | 5 | 6 => {
                let weekday: u8 = self.weekday.try_into().unwrap();
                Weekday::try_from(weekday).unwrap()
            }
            _ => unreachable!("This should not happen, weekday has DB check to make sure it's between 0 to 6."),
        }
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self { id: Set(Uuid::now_v7()), ..ActiveModelTrait::default() }
    }

    /// Will be triggered before insert / update
    async fn before_save<C>(self, _db: &C, _insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if self.weekday.as_ref() < &0 || self.weekday.as_ref() > &6 {
            Err(DbErr::Custom("[before_save] Invalid Weekday.".to_string()))
        } else {
            Ok(self)
        }
    }
}
