//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::action::Entity as Action;
pub use super::action_track::Entity as ActionTrack;
pub use super::ambition::Entity as Ambition;
pub use super::desired_state::Entity as DesiredState;
pub use super::diaries_tags::Entity as DiariesTags;
pub use super::diary::Entity as Diary;
pub use super::mindset::Entity as Mindset;
pub use super::reading_note::Entity as ReadingNote;
pub use super::reading_notes_tags::Entity as ReadingNotesTags;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
