//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::action::Entity as Action;
pub use super::ambition::Entity as Ambition;
pub use super::objective::Entity as Objective;
pub use super::record::Entity as Record;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
