//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action_track_type")]
pub enum ActionTrackType {
    #[sea_orm(string_value = "Count")]
    Count,
    #[sea_orm(string_value = "TimeSpan")]
    TimeSpan,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "timezone_enum")]
pub enum TimezoneEnum {
    #[sea_orm(string_value = "Asia/Tokyo")]
    AsiaTokyo,
    #[sea_orm(string_value = "UTC")]
    Utc,
}
