//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "timezone_enum")]
pub enum TimezoneEnum {
    #[sea_orm(string_value = "Asia/Tokyo")]
    AsiaTokyo,
    #[sea_orm(string_value = "UTC")]
    Utc,
}
