//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{cmp::Ordering, fmt::Display, str::FromStr};

use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr};
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(unique)]
    pub ambition_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub direction_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub action_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub name: Option<String>,
    pub r#type: TagType,
    #[sea_orm(belongs_to, from = "action_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub action_item: HasOne<super::action::Entity>,
    #[sea_orm(belongs_to, from = "ambition_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub ambition: HasOne<super::ambition::Entity>,
    #[sea_orm(belongs_to, from = "direction_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub direction: HasOne<super::direction::Entity>,
    #[sea_orm(belongs_to, from = "user_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub user: HasOne<super::user::Entity>,
    #[sea_orm(has_many, via = "diaries_tags")]
    pub diaries: HasMany<super::diary::Entity>,
    #[sea_orm(has_many, via = "reading_notes_tags")]
    pub reading_notes: HasMany<super::reading_note::Entity>,
    #[sea_orm(has_many, via = "thinking_note_tags")]
    pub thinking_notes: HasMany<super::thinking_note::Entity>,
}

#[derive(DeriveValueType, Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum TagType {
    Action,
    Ambition,
    Direction,
    Plain,
}

impl FromStr for TagType {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Action" => Ok(Self::Action),
            "Ambition" => Ok(Self::Ambition),
            "Direction" => Ok(Self::Direction),
            "Plain" => Ok(Self::Plain),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for TagType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Action => "Action",
                Self::Ambition => "Ambition",
                Self::Direction => "Direction",
                Self::Plain => "Plain",
            }
        )
    }
}

impl PartialOrd for TagType {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        self.ordering().partial_cmp(&other.ordering())
    }
}

impl Ord for TagType {
    fn cmp(&self, other: &Self) -> Ordering {
        self.ordering().cmp(&other.ordering())
    }
}

impl TagType {
    fn ordering(&self) -> u32 {
        match self {
            Self::Ambition => 0,
            Self::Direction => 1,
            Self::Action => 2,
            Self::Plain => 3,
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tag_type_cmp() -> Result<(), ()> {
        assert_eq!(Ordering::Equal, TagType::Ambition.cmp(&TagType::Ambition));
        assert_eq!(Ordering::Less, TagType::Ambition.cmp(&TagType::Direction));
        assert_eq!(Ordering::Less, TagType::Ambition.cmp(&TagType::Action));
        assert_eq!(Ordering::Less, TagType::Ambition.cmp(&TagType::Plain));

        assert_eq!(Ordering::Greater, TagType::Direction.cmp(&TagType::Ambition));
        assert_eq!(Ordering::Equal, TagType::Direction.cmp(&TagType::Direction));
        assert_eq!(Ordering::Less, TagType::Direction.cmp(&TagType::Action));
        assert_eq!(Ordering::Less, TagType::Direction.cmp(&TagType::Plain));

        assert_eq!(Ordering::Greater, TagType::Action.cmp(&TagType::Ambition));
        assert_eq!(Ordering::Greater, TagType::Action.cmp(&TagType::Direction));
        assert_eq!(Ordering::Equal, TagType::Action.cmp(&TagType::Action));
        assert_eq!(Ordering::Less, TagType::Action.cmp(&TagType::Plain));

        assert_eq!(Ordering::Greater, TagType::Plain.cmp(&TagType::Ambition));
        assert_eq!(Ordering::Greater, TagType::Plain.cmp(&TagType::Direction));
        assert_eq!(Ordering::Greater, TagType::Plain.cmp(&TagType::Action));
        assert_eq!(Ordering::Equal, TagType::Plain.cmp(&TagType::Plain));
        Ok(())
    }
}
