//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use chrono::{DateTime, FixedOffset, Utc};
use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr, ActiveValue::Set};
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub first_name: String,
    pub last_name: String,
    pub timezone: TimezoneEnum,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub first_track_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub actions: HasMany<super::action::Entity>,
    #[sea_orm(has_many)]
    pub action_goals: HasMany<super::action_goal::Entity>,
    #[sea_orm(has_many)]
    pub action_tracks: HasMany<super::action_track::Entity>,
    #[sea_orm(has_many)]
    pub ambitions: HasMany<super::ambition::Entity>,
    #[sea_orm(has_many)]
    pub diaries: HasMany<super::diary::Entity>,
    #[sea_orm(has_many)]
    pub directions: HasMany<super::direction::Entity>,
    #[sea_orm(has_many)]
    pub direction_categories: HasMany<super::direction_category::Entity>,
    #[sea_orm(has_many)]
    pub notification_rules: HasMany<super::notification_rule::Entity>,
    #[sea_orm(has_many)]
    pub reading_notes: HasMany<super::reading_note::Entity>,
    #[sea_orm(has_many)]
    pub tags: HasMany<super::tag::Entity>,
    #[sea_orm(has_many)]
    pub thinking_notes: HasMany<super::thinking_note::Entity>,
    #[sea_orm(has_one)]
    pub web_push_subscription: HasOne<super::web_push_subscription::Entity>,
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum TimezoneEnum {
    AsiaTokyo,
    Utc,
}

impl FromStr for TimezoneEnum {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Asia/Tokyo" => Ok(Self::AsiaTokyo),
            "UTC" => Ok(Self::Utc),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for TimezoneEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::AsiaTokyo => "Asia/Tokyo",
                Self::Utc => "UTC",
            }
        )
    }
}

impl TimezoneEnum {
    pub fn convert_utc(&self, datetime: DateTime<Utc>) -> DateTime<FixedOffset> {
        match self {
            TimezoneEnum::AsiaTokyo => datetime.with_timezone(&FixedOffset::east_opt(9 * 3600).unwrap()),
            TimezoneEnum::Utc => datetime.fixed_offset(),
        }
    }

    pub fn to_timezone_offset(&self) -> i32 {
        match self {
            TimezoneEnum::AsiaTokyo => 9,
            TimezoneEnum::Utc => 0,
        }
    }
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            created_at: Set(Utc::now().into()),
            updated_at: Set(Utc::now().into()),
            ..ActiveModelTrait::default()
        }
    }
}
