//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use chrono::{DateTime, FixedOffset, Utc};
use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub first_name: String,
    pub last_name: String,
    pub timezone: TimezoneEnum,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub first_track_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::action::Entity")]
    Action,
    #[sea_orm(has_many = "super::action_goal::Entity")]
    ActionGoal,
    #[sea_orm(has_many = "super::action_track::Entity")]
    ActionTrack,
    #[sea_orm(has_many = "super::ambition::Entity")]
    Ambition,
    #[sea_orm(has_many = "super::diary::Entity")]
    Diary,
    #[sea_orm(has_many = "super::direction::Entity")]
    Direction,
    #[sea_orm(has_many = "super::direction_category::Entity")]
    DirectionCategory,
    #[sea_orm(has_many = "super::notification_rule::Entity")]
    NotificationRule,
    #[sea_orm(has_many = "super::reading_note::Entity")]
    ReadingNote,
    #[sea_orm(has_many = "super::tag::Entity")]
    Tag,
    #[sea_orm(has_many = "super::thinking_note::Entity")]
    ThinkingNote,
    #[sea_orm(has_one = "super::web_push_subscription::Entity")]
    WebPushSubscription,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::action_goal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActionGoal.def()
    }
}

impl Related<super::action_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActionTrack.def()
    }
}

impl Related<super::ambition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ambition.def()
    }
}

impl Related<super::diary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Diary.def()
    }
}

impl Related<super::direction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Direction.def()
    }
}

impl Related<super::direction_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectionCategory.def()
    }
}

impl Related<super::notification_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationRule.def()
    }
}

impl Related<super::reading_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReadingNote.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl Related<super::thinking_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThinkingNote.def()
    }
}

impl Related<super::web_push_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebPushSubscription.def()
    }
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(value_type = "String")]
pub enum TimezoneEnum {
    AsiaTokyo,
    Utc,
}

impl FromStr for TimezoneEnum {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Asia/Tokyo" => Ok(Self::AsiaTokyo),
            "UTC" => Ok(Self::Utc),
            _ => Err(ValueTypeErr),
        }
    }
}

impl Display for TimezoneEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::AsiaTokyo => "Asia/Tokyo",
                Self::Utc => "UTC",
            }
        )
    }
}

impl TimezoneEnum {
    pub fn convert_utc(&self, datetime: DateTime<Utc>) -> DateTime<FixedOffset> {
        match self {
            TimezoneEnum::AsiaTokyo => datetime.with_timezone(&FixedOffset::east_opt(9 * 3600).unwrap()),
            TimezoneEnum::Utc => datetime.fixed_offset(),
        }
    }

    pub fn to_timezone_offset(&self) -> i32 {
        match self {
            TimezoneEnum::AsiaTokyo => 9,
            TimezoneEnum::Utc => 0,
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
