[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[lib]
name = "settings"
path = "lib.rs"

[dependencies]
config.workspace = true
minijinja.workspace = true
once_cell.workspace = true
serde.workspace = true